name: Update Dockerfiles

on:
  workflow_dispatch:

jobs:
  update-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show current Dockerfiles
        run: |
          echo "Before update:"
          find . -name "Dockerfile" -exec cat {} \;

      - name: Run update script
        run: |
          find . -name "Dockerfile" | while read file; do
              echo "Updating $file..."
              echo "--- Before ---"
              cat "$file"
              # Replace any python:3.9 with python:3.11 (handles minor versions and tags)
              sed -i -E 's|python:3\.9([^\s]*)|python:3.11\1|g' "$file"
              echo "--- After ---"
              cat "$file"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

          git checkout -B update-dockerfiles
          git add .
          git commit -m "Bulk update of Dockerfiles from Python 3.9 to 3.11"
          git push origin update-dockerfiles --force
