name: Bulk Update Dockerfiles

on:
  workflow_dispatch:

permissions:
  contents: write    # ✅ allow workflow to push commits
#  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run update script
        run: |
          find . -name "Dockerfile" | while read file; do
              sed -i 's|python:3.9|python:3.11|g' "$file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b update-dockerfiles
          git add -- ':!.github/workflows/*'
          git commit -m "Bulk update of Dockerfiles"
          git push origin update-dockerfiles
